### ISSUE TITLE
Issues with python 3.8.8

### ISSUE THREAD

**Issue by yeastbeast** [bschulzlab/DIALib#18]
Hi, 
I cannot get the backend to run under python 3.8.8:

Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32

>python main.web.py
Traceback (most recent call last):
  File "main.web.py", line 572, in <module>
    application.listen(options.p)
  File "C:\Users\kamrads\Anaconda3\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\kamrads\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\kamrads\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\kamrads\Anaconda3\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\kamrads\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\kamrads\Anaconda3\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

In a fresh conda environment with python 3.6 it worked fine though.

**Comment by noatgnu** [comment]
Hi, I believe this is due to changes to asyncio that we would need to include this in main body
```python
import asyncio
import sys

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
